FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y install apt-utils ca-certificates
COPY sispop-deb-key.gpg /etc/apt/trusted.gpg.d/sispop.gpg
RUN echo "deb https://deb.sispop.io focal main" > /etc/apt/sources.list.d/sispop.list && \
    apt-get update
